### ISSUE TITLE
Segmentation fault on recluster in phy

### ISSUE THREAD

**Issue by mspacek** [klusta-team/klustakwik2#74]
I'm exactly sure how the "recluster" in phy command is supposed to work, but all I ever get is a segfault, which I think is happening in kk2. This is irrespective of the dataset, the cluster selected for reclustering, or the machine that I try it on (running Xubuntu 14.04 and 16.04). I always get something like this:

```
$ phy kwik-gui hybrid_10sec.kwik
17:08:40 [I] gui:95               Running KlustaKwik on 20 spikes.
17:08:40 [I] launch:118           Resuming KK from `/home/user/data/klusta/.klustakwik2/spike_clusters.0.txt` (18 clusters)...
17:08:40 [I] launch:120           If you want to restart the clustering, delete `/home/user/data/klusta/.klustakwik2/spike_clusters.0.txt`.
17:08:40 [I] klustakwik KlustaKwik2 version git-0.2.4-6-g6164fbdf
17:08:40 [I] klustakwik.initial_parameters use_noise_cluster = True
17:08:40 [I] klustakwik.initial_parameters subset_break_fraction = 0.01
17:08:40 [I] klustakwik.initial_parameters full_step_every = 1
17:08:40 [I] klustakwik.initial_parameters num_changed_threshold = 0.05
17:08:40 [I] klustakwik.initial_parameters use_mua_cluster = True
17:08:40 [I] klustakwik.initial_parameters penalty_k = 0.0
17:08:40 [I] klustakwik.initial_parameters split_every = 40
17:08:40 [I] klustakwik.initial_parameters break_fraction = 0.0
17:08:40 [I] klustakwik.initial_parameters always_split_bimodal = False
17:08:40 [I] klustakwik.initial_parameters consider_cluster_deletion = True
17:08:40 [I] klustakwik.initial_parameters points_for_cluster_mask = 100
17:08:40 [I] klustakwik.initial_parameters max_split_iterations = None
17:08:40 [I] klustakwik.initial_parameters fast_split = False
17:08:40 [I] klustakwik.initial_parameters split_first = 20
17:08:40 [I] klustakwik.initial_parameters mua_point = 2
17:08:40 [I] klustakwik.initial_parameters max_quick_step_candidates_fraction = 0.4
17:08:40 [I] klustakwik.initial_parameters dist_thresh = 9.21034037198
17:08:40 [I] klustakwik.initial_parameters max_iterations = 1000
17:08:40 [I] klustakwik.initial_parameters max_possible_clusters = 1000
17:08:40 [I] klustakwik.initial_parameters num_cpus = None
17:08:40 [I] klustakwik.initial_parameters penalty_k_log_n = 1.0
17:08:40 [I] klustakwik.initial_parameters max_quick_step_candidates = 100000000
17:08:40 [I] klustakwik.initial_parameters num_starting_clusters = 10
17:08:40 [I] klustakwik.initial_parameters prior_point = 1
17:08:40 [I] klustakwik.initial_parameters noise_point = 1
17:08:40 [I] klustakwik Clustering data set of 20 points, 96 features
17:08:40 [I] klustakwik Starting iteration 0 with 19 clusters
Segmentation fault (core dumped)
```

On both machiens, I'm using the latest versions of kk2, klusta, phy and phy-contrib from git. Can the recluster command that launches kk2 be intercepted with gdb or something? I would guess the segfault is happening in some Cython code.

**Comment by rossant** [comment]
Should be fixed in https://github.com/kwikteam/phy-contrib/pull/75 feel free to try and close if it works. You need the latest development version of klusta too.

**Comment by mspacek** [comment]
Thanks Cyrille, but I'm still getting the segfault. I'm on the latest kk2, phy-contrib, phy and klusta. I  even tried deleting all klusta output files and folders and rerunning `klusta hybrid_10sec.dat`, and then `phy kwik-gui hybrid_10sec.kwik`, but the recluster command still crashes phy, and the segfault still happens after iteration 0 begins:

```
$ phy kwik-gui hybrid_10sec.kwik
11:15:27 [I] gui:38               Backup `/home/user/data/klusta/hybrid_10sec.kwik.bak`.
11:15:34 [I] gui:95               Running KlustaKwik on 19 spikes.
11:15:34 [I] launch:118           Resuming KK from `/home/user/data/klusta/.klustakwik2/spike_clusters.0.txt` (18 clusters)...
11:15:34 [I] launch:120           If you want to restart the clustering, delete `/home/user/data/klusta/.klustakwik2/spike_clusters.0.txt`.
11:15:34 [I] klustakwik KlustaKwik2 version git-0.2.4-6-g6164fbdf
11:15:34 [I] klustakwik.initial_parameters use_noise_cluster = True
11:15:34 [I] klustakwik.initial_parameters subset_break_fraction = 0.01
11:15:34 [I] klustakwik.initial_parameters full_step_every = 1
11:15:34 [I] klustakwik.initial_parameters num_changed_threshold = 0.05
11:15:34 [I] klustakwik.initial_parameters use_mua_cluster = True
11:15:34 [I] klustakwik.initial_parameters penalty_k = 0.0
11:15:34 [I] klustakwik.initial_parameters split_every = 40
11:15:34 [I] klustakwik.initial_parameters break_fraction = 0.0
11:15:34 [I] klustakwik.initial_parameters always_split_bimodal = False
11:15:34 [I] klustakwik.initial_parameters consider_cluster_deletion = True
11:15:34 [I] klustakwik.initial_parameters points_for_cluster_mask = 100
11:15:34 [I] klustakwik.initial_parameters max_split_iterations = None
11:15:34 [I] klustakwik.initial_parameters fast_split = False
11:15:34 [I] klustakwik.initial_parameters split_first = 20
11:15:34 [I] klustakwik.initial_parameters mua_point = 2
11:15:34 [I] klustakwik.initial_parameters max_quick_step_candidates_fraction = 0.4
11:15:34 [I] klustakwik.initial_parameters dist_thresh = 9.21034037198
11:15:34 [I] klustakwik.initial_parameters max_iterations = 1000
11:15:34 [I] klustakwik.initial_parameters max_possible_clusters = 1000
11:15:34 [I] klustakwik.initial_parameters num_cpus = None
11:15:34 [I] klustakwik.initial_parameters penalty_k_log_n = 1.0
11:15:34 [I] klustakwik.initial_parameters max_quick_step_candidates = 100000000
11:15:34 [I] klustakwik.initial_parameters num_starting_clusters = 10
11:15:34 [I] klustakwik.initial_parameters prior_point = 1
11:15:34 [I] klustakwik.initial_parameters noise_point = 1
11:15:34 [I] klustakwik Clustering data set of 19 points, 96 features
11:15:34 [I] klustakwik Starting iteration 0 with 19 clusters
Segmentation fault (core dumped)
```

**Comment by rossant** [comment]
Have you pulled the phycontrib PR?

**Comment by mspacek** [comment]
Whoops, I only pulled from phy-contrib master, somehow didn't notice that master hadn't even changed. Yes, that works now. Thanks!

**Comment by rossant** [comment]
Great! Closing.
